import Head from 'next/head';


export default function Home() {
  return (
    <main className="d-flex flex-column min-vh-100">
      <Head>
         <title>Rubieże</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
      </Head>

    </main>
    <footer>
       
    </footer>
  );
}